apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bottin-scolaire
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bottin-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: http://backend:8000/api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bottin-scolaire
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  nodePort: 30001
