apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: bottin-scolaire
type: Opaque
stringData:
  MONGO_URL: "REPLACE_WITH_MONGO_URL"
  JWT_SECRET: "REPLACE_WITH_JWT_SECRET"
  ADMIN_EMAIL: "REPLACE_WITH_ADMIN_EMAIL"
  ADMIN_PASSWORD: "REPLACE_WITH_ADMIN_PASSWORD"
